version: "3.8"

services:
  lct_frontend:
    container_name: lct_frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.teams=LCT
    networks:
      - lct-net

networks:
  lct-net:
    external: true
