services:
    lct_front:
        container_name: lct_front
        build:
            context: .
            dockerfile: Dockerfile
        command: ["nginx", "-g", "daemon off;"]
        ports:
            - "${APP_PORT}:80"
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=LCT
